### PR TITLE
Adding Google Analytics

### PR DESCRIPTION
**Pull request by johnbradley**

### CODE REVIEW

**Comment by hlapp** [comment]
@johnbradley I would put that near the end of the page loading, for example just before or close to the closing `</body>` tag, so that delays in loading the Analytics code don't delay the page loading.

**Comment by johnbradley** [comment]
@hlapp I was originally going to do that but google's instructions https://support.google.com/analytics/answer/1008080?hl=en  specify 
`before the closing </head>`.

**Comment by johnbradley** [comment]
I did some testing and it looks like the analytics takes between 100 - 300 ms.
I'm going to move it to the bottom.

**Comment by hlapp** [comment]
> @hlapp I was originally going to do that but google's instructions https://support.google.com/analytics/answer/1008080?hl=en specify 
> before the closing </head>.

I know they do, but they actually normally work just as well at the bottom :-)

**Pull request merged**
