### PR TITLE
Color dna

### PR DESCRIPTION
**Pull request by johnbradley**
Changes to add colors to dna sequences in prediction details popup.

### CODE REVIEW

**Comment by johnbradley** [comment]
@dleehr Do you mind reviewing these changes?

**Comment by dleehr** [comment]
Guess I need to learn some @reactjs then

**Comment by dleehr** [comment]
👍

**Comment by dleehr** [comment]
Here's a scheme to try, via http://paletton.com/palette.php?uid=7051e0kvEpKlXwgseuTAel3IOfP

```
const CHAR_TO_COLOR = {
    'A': '#02992A',
    'C': '#25148E',
    'G': '#CDA302',
    'T': '#CD1A02',
};

```

**Comment by dleehr** [comment]
From http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-15-52

```
const CHAR_TO_COLOR = {
    'A': '#00d000',
    'C': '#0729d3',
    'G': '#fdbc00',
    'T': '#d71f00',
};
```

**Pull request merged**
